from django.urls import path
from . import views
 
urlpatterns = [
    path('register/', views.user_registration_view, name='add-accounts'),
    path('alla/', views.view_account, name='view-accounts'),
    path('login/', views.user_login_view, name='login-accounts'),
    path('updatea/<int:pk>/', views.update_accounts, name='update-accounts'),
    path('createsp/', views.add_service_provider, name='add-service-provider'),
    path('allsp/', views.view_service_provider, name='view-service-provider'),
    path('updatesp/<int:pk>/', views.update_service_provider, name='update-service-provider'),
    path('sp/<int:pk>/delete/', views.delete_service_provider, name='delete-service-provider'),
    path('createp/', views.add_partner, name='add-partner'),
    path('allp/', views.view_partner, name='view-partner'),
    path('updatep/<int:pk>/', views.update_partner, name='update-partner'),
    path('partner/<int:pk>/delete/', views.delete_partner, name='delete-partner'),
    path('creates/', views.add_service, name='add-service'),
    path('alls/', views.view_service, name='view-service'),
    path('updates/<int:pk>/', views.update_service, name='update-service'),
    path('service/<int:pk>/delete/', views.delete_service, name='delete-service'),
    path('createb/', views.add_bill, name='add-bill'),
    path('allb/', views.view_bill, name='view-bill'),
    path('updateb/<int:pk>/', views.update_bill, name='update-bill'),
    path('bill/<int:pk>/delete/', views.delete_bill, name='delete-bill'),
    path('createpe/', views.add_partner_employe, name='add-partner-employe'),
    path('allpe/', views.view_partner_employe, name='view-partner-employe'),
    path('updatepe/<int:pk>/', views.update_partner_employe, name='update-partner-employe'),
    path('pe/<int:pk>/delete/', views.delete_partner_employe, name='delete-partner-employe'),
    path('createps/', views.add_partner_service, name='add-partner-service'),
    path('allps/', views.view_partner_service, name='view-partner-service'),
    path('updateps/<int:pk>/', views.update_partner_service, name='update-partner-service'),
    path('ps/<int:pk>/delete/', views.delete_partner_service, name='delete-partner-service'),
    path('createbp/', views.add_bill_partner, name='add-bill-partner'),
    path('allbp/', views.view_bill_partner, name='view-bill-partner'),
    path('updatebp/<int:pk>/', views.update_bill_partner, name='update-bill-partner'),
    path('bp/<int:pk>/delete/', views.delete_bill_partner, name='delete-bill-partner'),
]
